MyToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Data.Edm.Library;
using MyToDoList.Entities;
using MyToDoList.Enums;
using MyToDoList.Models;
using MyToDoList.Services;
using MyToDoList.ViewModels.HomeViewModels;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;


namespace MyToDoList.Controllers
{
    public class HomeController:Controller
    {
        private IDbContextService _dbContextService;
        private ICategoryRepository _categoryRepository;
        private ICurrentWeekService _currentWeekService;
        private IAmmountOfDoneDutiesArchiveRepository _ammountOfDoneDutiesArchiveRepository;
        private IOverdueDutyRepository _overdueDutyRepository;
        private IDutyRepository _dutyRepository;

        public HomeController(IDutyRepository dutyRepository,
            ICategoryRepository categoryRepository,
            IDbContextService dbContextService,
            ICurrentWeekService currentWeekService,
            IAmmountOfDoneDutiesArchiveRepository ammountOfDoneDutiesArchiveRepository,
            IOverdueDutyRepository overdueDutyRepository)
        {
            _overdueDutyRepository = overdueDutyRepository;
            _dutyRepository = dutyRepository;
            _dbContextService = dbContextService;
            _categoryRepository = categoryRepository;
            _currentWeekService = currentWeekService;
            _ammountOfDoneDutiesArchiveRepository = ammountOfDoneDutiesArchiveRepository;
            
        }
        [HttpGet]
        [ImportModelState]
        public IActionResult Index()
        {
            CurrentWeek currentWeek = _currentWeekService.GetCurrentWeek();

            if(currentWeek==null)
            {
                throw new Exception("currentWeek doesn't exist");

            }

            if (!DoesDateLiesInCurrentWeek(currentWeek.Date))
            {
                _ammountOfDoneDutiesArchiveRepository.ResetArchive();

                var duties = _dutyRepository.Duties;

                foreach(var duty in duties)
                {
                    var overdueDuty = new OverdueDuty()
                    {
                        Content = duty.Content,
                        Category = duty.Category,
                        CategoryId = duty.CategoryId
                    };

                    _overdueDutyRepository.AddOverdueDuty(overdueDuty);


                    _dutyRepository.RemoveDuty(duty);
                }

                currentWeek.Date = DateTime.Now;

                _dbContextService.Commit();
            }

            var model = new IndexViewModel()
            {
                CurrentWeek = currentWeek,
                OverdueDuties = _overdueDutyRepository.OverdueDuties
            };

            return View(model);

        }

        [HttpPost]
        [ExportModelState]
      
        public IActionResult AddDuty(string StringDay,DayViewModel model)
        {
            var category = _categoryRepository.GetCategory(model.DutyCategoryId);

            if (category == null)
            {

                ModelState.AddModelError("", "Każde zadanie musi przynależeć do kategorii. Stwórz nową kategorię, a następnie dodaj do niej zadanie.");
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }

            Day DayForCreate=Day.Monday;
            bool StringDayMatchedFlag = false;

            foreach(Day day in Enum.GetValues(typeof(Day)))
            {
                if(StringDay==day.ToString())
                {
                    DayForCreate = day;
                    StringDayMatchedFlag = true;
                    break;
                }
            }

            if(!StringDayMatchedFlag)
            {
                throw new Exception("StringDay hasn't matched");
            }

            var newDuty = new Duty()
            {
                Content = model.Content,
                Day = DayForCreate,
                Category = category
                
            };
            

            _dutyRepository.AddDuty(newDuty);

            _dbContextService.Commit();

            return RedirectToAction("Index","Home");
        }
        [HttpPost]
        [ExportModelState]
        public IActionResult AddCategory(CategoryViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }
            var newCategory = new Category()
            {
                Name = model.NewCategoryName
            };

            _categoryRepository.AddCategory(newCategory);

            _dbContextService.Commit();

            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult RemoveDuty(int id)
        {
            var duty = _dutyRepository.GetDuty(id);

            if(duty==null)
            {
                throw new Exception("No such duty");
            }

            _dutyRepository.RemoveDuty(duty);

            _dbContextService.Commit();

            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult ExecuteDuty(int id)
        {
            var duty = _dutyRepository.GetDuty(id);

            if(duty==null)
            {
                if (duty == null)
                {
                    throw new Exception("No such duty");
                }
            }

            _ammountOfDoneDutiesArchiveRepository.AddDoneDuty(duty);

            _dutyRepository.RemoveDuty(duty);

            _dbContextService.Commit();

            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult ExecuteOverdueDuty(int id)
        {
            var overdueDuty = _overdueDutyRepository.GetOverdueDuty(id);

            if(overdueDuty==null)
            {
                throw new Exception("No such OverdueDuty");
            }

            _ammountOfDoneDutiesArchiveRepository.AddDoneOverdueDuty();

            _overdueDutyRepository.RemoveOverdueDuty(overdueDuty);

            _dbContextService.Commit();

            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult RemoveOverdueDuty(int id)
        {
            var overdueDuty = _overdueDutyRepository.GetOverdueDuty(id);

            if (overdueDuty == null)
            {
                throw new Exception("No such OverdueDuty");
            } 

            _overdueDutyRepository.RemoveOverdueDuty(overdueDuty);

            _dbContextService.Commit();

            return RedirectToAction("Index", "Home");
        }
        public IActionResult ChangeDutyDay(string id,string Day)
        {
            Day newDay = Enums.Day.Monday;
           foreach(Day day in Enum.GetValues(typeof(Day)))
            {
                if(day.ToString()==Day)
                {
                    newDay = day;
                    break;
                }
            }

            var duty = _dutyRepository.GetDuty(Int32.Parse(id));

            if(duty ==null)
            {
                throw new Exception("Duty doesn't exist");
            }

            duty.Day = newDay;

            _dbContextService.Commit();

            return RedirectToAction("Index", "Home");
        }
        bool DoesDateLiesInCurrentWeek(DateTime date)
        { 
            DateTime startOfWeek = DateTime.Today;

            while(startOfWeek.DayOfWeek!= DayOfWeek.Monday)
            {
                startOfWeek = startOfWeek.AddDays(-1);
            }

            DateTime endOfWeek = startOfWeek.AddDays(6);

            if(date>=startOfWeek&&date<=endOfWeek)
            {
                return true;
            }
            return false;
            
        }
    
    }

}

MyToDoList/ViewComponents/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyToDoList.Services;
using MyToDoList.ViewModels.HomeViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyToDoList.ViewComponents
{
    public class CategoryViewComponent:ViewComponent
    {
        private ICategoryRepository _categoryRepository;
        private IDutyRepository _dutyRepository;
        private IAmmountOfDoneDutiesArchiveRepository _ammountOfDoneDutiesArchiveRepository;

        public CategoryViewComponent(
            ICategoryRepository categoryRepository,
            IDutyRepository dutyRepository,
            IAmmountOfDoneDutiesArchiveRepository ammountOfDoneDutiesArchiveRepository)
        {
            _categoryRepository = categoryRepository;
            _dutyRepository = dutyRepository;
            _ammountOfDoneDutiesArchiveRepository = ammountOfDoneDutiesArchiveRepository;
        }
        public IViewComponentResult Invoke()
        {
            var model = new CategoryViewModel()
            {
                Duties = _dutyRepository.Duties,
                Categories = _categoryRepository.Categories,
                Archive = _ammountOfDoneDutiesArchiveRepository.GetArchive()
            };

            return View(model);
        }
    }
}

MyToDoList/ViewComponents/ChangeDayViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyToDoList.Enums;
using MyToDoList.Services;
using MyToDoList.ViewModels.SharedViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyToDoList.ViewComponents
{
    public class ChangeDayViewComponent:ViewComponent
    {
        private IDutyRepository _dutyRepository;

        public ChangeDayViewComponent(IDutyRepository dutyRepository)
        {
            _dutyRepository = dutyRepository;
        }
        public IViewComponentResult Invoke(Day day,int dutyId,string dayNameToDisplay)
        {

            var model = new ChangeDayViewModel()
            {
                DutyId = dutyId,
                Day = day,
                DayNameToDisplay = dayNameToDisplay

            };


            return View(model);
        }
    }
}

MyToDoList/ViewComponents/DayViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyToDoList.Enums;
using MyToDoList.Services;
using MyToDoList.ViewModels.HomeViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyToDoList.ViewComponents
{
    public class DayViewComponent:ViewComponent
    {
        private ICategoryRepository _categoryRepository;
        private IDutyRepository _dutyReposiotory;


        public DayViewComponent(IDutyRepository dutyRepository,ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
            _dutyReposiotory = dutyRepository;
        }
        public IViewComponentResult Invoke()
        {
            var model = new DayViewModel()
            {
                Duties = _dutyReposiotory.Duties,
                Categories = _categoryRepository.Categories
            };            
            return View(model);
        }
    }
}

MyToDoList/Views/Home/Index.cshtml
@model MyToDoList.ViewModels.HomeViewModels.IndexViewModel
@{
    ViewBag.Title = "MyToDoList";
}
<head>
    <link href="~/Styles/Home-Index.css" rel="stylesheet" />
</head>
<div id="ValSum" asp-validation-summary="All">

</div>
<h1>@Model.CurrentWeek.Date.Date</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8">
            @if (Model.OverdueDuties.Any())
            {
                var iteration = 0;
            <div id="OverDueDuties" class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Zaległe</h3>
                    </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <tr>
                            <th style="text-align:center;" class="col-sm-1">#</th>
                            <th class="col-sm-6">Treść</th>
                            <th class="col-sm-3">Kategoria</th>
                            <th style="text-align:center;" class="col-sm-1">Wykonaj</th>
                            <th style="text-align:center;" class="col-sm-1">Inne</th>
                        </tr>
                        @foreach (var duty in Model.OverdueDuties)
                        {
                            iteration++;
                            <form method="post">
                                    <tr>
                                        <td style="text-align:center;">@iteration</td>
                                        <td>@duty.Content</td>
                                        <td>@duty.Category.Name</td>
                                        <td align="center">
                                            <button type="submit" class="btn btn-default InvisibleButton" asp-action="ExecuteOverdueDuty" asp-controller="Home" asp-route-id="@duty.Id">
                                                <span  class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                        <td align="center">
                                            <div class="dropdown">
                                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                    ...
                                                    <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

                                                    <li>
                                                        <button type="submit" class="btn btn-danger" asp-action="RemoveDuty" asp-controller="Home" asp-route-id="@duty.Id">
                                                            Usuń
                                                        </button>
                                                    </li>
                                                    <li class="dropdown-header">Przenieś na:</li>
                                                    <li>
                                                        @await Component.InvokeAsync("ChangeDay", new { day = Day.Monday, dutyId = duty.Id, dayNameToDisplay = "Poniedziałek" })
                                                    </li>
                                                    <li>
                                                        @await Component.InvokeAsync("ChangeDay", new { day = Day.Tuesday, dutyId = duty.Id, dayNameToDisplay = "Wtorek" })
                                                    </li>
                                                    <li>
                                                        @await Component.InvokeAsync("ChangeDay", new { day = Day.Wednesday, dutyId = duty.Id, dayNameToDisplay = "Środa" })
                                                    </li>
                                                    <li>
                                                        @await Component.InvokeAsync("ChangeDay", new { day = Day.Thursday, dutyId = duty.Id, dayNameToDisplay = "Czwartek" })
                                                    </li>
                                                    <li>
                                                        @await Component.InvokeAsync("ChangeDay", new { day = Day.Friday, dutyId = duty.Id, dayNameToDisplay = "Piątek" })
                                                    </li>
                                                    <li>
                                                        @await Component.InvokeAsync("ChangeDay", new { day = Day.Saturday, dutyId = duty.Id, dayNameToDisplay = "Sobota" })
                                                    </li>
                                                    <li>
                                                        @await Component.InvokeAsync("ChangeDay", new { day = Day.Sunday, dutyId = duty.Id, dayNameToDisplay = "Niedziela" })
                                                    </li>

                                                </ul>
                                            </div>

                                        </td>
                                    </tr>
                            </form>

                        }
                    </table>
                </div>
                </div>
            }
                    @await Component.InvokeAsync("Day");
                </div>
                <div class="col-sm-4">
                    @await Component.InvokeAsync("Category")
                </div>

            </div>
        </div>